# Generated by Django 4.2.7 on 2023-11-28 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostavailability',
            options={'verbose_name_plural': 'Host Availabilities'},
        ),
        migrations.RemoveField(
            model_name='hostavailability',
            name='guest',
        ),
        migrations.AddField(
            model_name='hostavailability',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
