# Generated by Django 4.2.7 on 2023-11-28 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hha', '0002_alter_hostavailability_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hha.guest')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hha.host')),
            ],
        ),
    ]
