# Generated by Django 4.2.7 on 2023-11-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hha', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hha.guest'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hha.host'),
        ),
        migrations.AlterField(
            model_name='hostavailability',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hha.host'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('host', 'guest', 'date'), ('guest', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='hostavailability',
            unique_together={('host', 'date')},
        ),
    ]
